import type { Metadata } from "next";
import "@/styles/globals.css";
import ScrollBtn from "@/components/shared/ScrollBtn";
import { Toaster } from "sonner";
import "../../node_modules/flag-icons/css/flag-icons.min.css";

export const metadata: Metadata = {
  title: "America Working",
  description: "Generated by create next app",
  icons: {
    icon: "/images/Logo.webp",
  },
};

export default async function LocaleLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning>
      <body
        // className={`${roboto.variable} ${inter.variable} ${sfProDisplay.variable} antialiased`}
        className={`antialiased`}
      >
        <ScrollBtn />
        <Toaster position="top-right" expand={false} richColors />
        {children}
      </body>
    </html>
  );
}
