import type { Metadata } from "next";
import "../../styles/globals.css";
import { roboto, inter, sfProDisplay } from "@/Fonts/Font";
import "../../../node_modules/flag-icons/css/flag-icons.min.css";
import { Toaster } from "sonner";
import ScrollBtn from "@/components/shared/ScrollBtn";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
  title: "America Working",
  description: "Generated by create next app",
  icons: {
    icon: "/images/Logo.png",
  },
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {

  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${roboto.variable} ${inter.variable} ${sfProDisplay.variable} antialiased`}
      >
        <NextIntlClientProvider  >
          <ScrollBtn />
          <Toaster position="top-right" expand={false} richColors />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
