import type { Metadata } from "next";
import "../../styles/globals.css";
import { roboto, inter, sfProDisplay } from "@/Fonts/Font";
import "../../../node_modules/flag-icons/css/flag-icons.min.css";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { Toaster } from "sonner";
import ScrollBtn from "@/components/shared/ScrollBtn";
import { NextIntlClientProvider } from "next-intl";

export const metadata: Metadata = {
  title: "America Working",
  description: "Generated by create next app",
  icons: {
    icon: "/images/Logo.png",
  },
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  let messages;
  try {
    messages = await getMessages({ locale });
  } catch {
    notFound();
  }

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${roboto.variable} ${inter.variable} ${sfProDisplay.variable} antialiased`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ScrollBtn />
          <Toaster position="top-right" expand={false} richColors />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
